version: 2
jobs:
  build:
    docker:
#      - image: quay.io/3scale/s2i-openresty-centos7:luarocks-build
       - image: jfernandes/circleci-node-lua:v1.0.0
    steps:
      - checkout

      # install lua interpreter and luarocks
      - run: sudo apt-get install lua5.1 luarocks

      # Installation process:

        # xml needs libstdc++6 (- sudo apt-get install libstdc++6)
        # zip needs libzzip-0.so.13

        # Install latest framework version from master:
      - run: git clone https://github.com/lidesdk/shell.git $PWD/shell --recursive
      #- run: export LIDE_PATH=/home/circleci/project/shell

        # Runtime system libraries /usr/lib/x86_64-linux-gnu/
      - run: sudo cp $PWD/shell/clibs/linux/x64/pcaf_libstdc++.so.6 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
      - run: sudo cp $PWD/shell/clibs/linux/x64/pcaf_libzzip-0.so.13 /usr/lib/x86_64-linux-gnu/libzzip-0.so.13 

        # Default lua interpreter
      - run: chmod +x $LIDE_PATH/bin/linux/x64/lua

      # Preparing environment:

      - run: $LIDE_PATH/lide.sh install http && $LIDE_PATH/lide.sh tests/http_test.lua